### ISSUE TITLE
UI Review

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [sgreenholtz/Pattern-Partner#1]
Great job getting a good start on the screens!
- [ ] Does this provide you with enough to decide what database tables/fields you will need?
- [ ] Are you thinking you will use a responsive design so this could also work on any size screen? I think we decided the UI details might be out a bit in the schedule, but I thought of it as I was looking at this. Have you worked with Bootstrap at all?
- [ ] Is the font large enough for somebody to see while they are working?
- [ ] Thoughts on the add/save screen? Can users enter all their own details?

**Comment by sgreenholtz** [comment]
1. I think I know what database tables and fields I'll need, though I haven't really thought about it yet so I'm not sure how exactly I want to save each pattern, or what's the best way to divide out each line in each file.
2. Definitely planning on using responsive design. I have used pre-made Bootstrap themes using Bootswatch in my PHP class but not with Bootstrap itself.
3. The font might need to be a little larger, but it's close to what it shouldactually be. I think a feature to increase the font size would be super useful.
4. I didn't do an add/save screen because I'm not sure what kind of file choice functionality is possible, thinking about PDF files. Specifically, I don't know if there should be a URL and file selection option or just one or the other. Users can enter their own details and pick a cover photo.
